name: kmol
channels:
  - zeroae
  - mordred-descriptor
  - pyg
  - pytorch
  - nvidia/label/cuda-11.7.0
  - conda-forge
  - acellera
  - defaults
dependencies:
  - biopython=1.81
  - cairosvg=2.5.2
  - captum=0.5.0
  - cuda=11.7.0
  - cudatoolkit=11.7.0
  - cython=0.29.33
  - dask=2023.4.0=pyhd8ed1ab_0
  - distributed=2023.4.0=pyhd8ed1ab_0
  - dm-tree=0.1.6
  - grpcio-tools=1.54.2
  - grpcio=1.54.2
  - libprotobuf=3.21.12
  - mordred=1.2.0
  - networkx=2.5.1
  - numpy=1.24.1
  - openpyxl=3.1.1
  - optuna=2.4.0
  - pandas=1.5.2
  - pyg=2.3.0
  - pyhumps=1.6.1
  - python=3.9.17
  - python_abi=3.9
  - pytorch-cluster=1.6.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.1
  - pytorch-sparse=0.6.16
  - pytorch-spline-conv=1.2.2
  - pytorch=1.13.1
  - rdkit=2022.9.4
  - requests=2.26.0
  - rich=12.6.0
  - scikit-learn=1.2.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - typing-extensions=4.3.0
  - moleculekit=1.7.7
  - openbabel=3.1.1
  - ambertools=22.0
  - biopandas=0.4.1
  - mdanalysis=2.5.0
  - mkl=2024.0.0
