name: kmol-lrodd
channels:
  - zeroae
  - mordred-descriptor
  - pytorch
  - conda-forge
  - pyg
  - dask/label/dev
  - defaults
  - nvidia
dependencies:
  - cuda=11.7.1
  - openssl>=1.1.1i,<1.1.2a
  - libprotobuf=3.13.0.1
  - python=3.9.1
  - pip
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pyg=2.2.0
  - scikit-learn=1.2.1
  - numpy=1.24.1
  - dask=2023.2.1a230224
  - distributed=2023.2.1a230224
  - networkx=2.5.1
  - rdkit=2022.9.4
  - pandas=1.5.2
  - cython=0.29.33
  - mordred=1.2.0
  - grpcio=1.35.0
  - grpcio-tools=1.35.0
  - optuna=2.4.0
  - cairosvg=2.5.2
  - pyhumps=1.6.1
  - rich=12.6.0
  - openpyxl
  - biopython=1.79
  - dm-tree=0.1.6
  - requests=2.26.0
  - typing-extensions=4.3.0
  - captum=0.5.0
