name: kmol
channels:
  - zeroae
  - mordred-descriptor
  - pytorch
  - conda-forge
  - defaults
  - nvidia/label/cuda-11.7.0
dependencies:
  - cuda=11.7.0
  - openssl=1.1.1h
  - libprotobuf=3.13.0.1
  - python=3.9.1
  - pip
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
