[build-system]
requires = ["setuptools>=42", "wheel", "cython", "numpy", "torch"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 128

[tool.flake8]
ignore = ['E203']
max-line-length = 128
